filepath: examples/bvh/rokoko/shortsquat.bvh
start_frame_idx: 100
end_frame_idx: 226
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.00001
up: +y
